services:
  db:
    image: bitnami/mysql:latest
    container_name: mysql_db
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_ROOT_PASSWORD= # root bez hesla
      - MYSQL_DATABASE=laravel_db
      - MYSQL_USER=laravel
      - MYSQL_PASSWORD=laravel
    ports:
      - "3306:3306"
    volumes:
      - db_data:/bitnami/mysql
    networks:
      - app-network

  laravel:
    image: bitnami/laravel:latest
    container_name: laravel_app
    depends_on:
      - db
    volumes:
      - ./laravel:/app
    environment:
      - LARAVEL_DATABASE_HOST=db
      - LARAVEL_DATABASE_USER=laravel
      - LARAVEL_DATABASE_PASSWORD=laravel
      - LARAVEL_DATABASE_NAME=laravel_db
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "8000:8000"
    networks:
      - app-network

  svelte:
    build:
      context: ./svelte
      dockerfile: Dockerfile
    container_name: svelte_app
    volumes:
    - ./svelte/src:/usr/src/app/src
    - ./svelte/public:/usr/src/app/public
    ports:
      - "8080:8080"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
